SELECT * FROM BOARD;
SELECT * FROM BOARD_IMG;

SELECT BOARD_CONTENT FROM BOARD WHERE BOARD_CONTENT LIKE '가%';
SELECT COUNT(*) FROM BOARD WHERE BOARD_CONTENT LIKE '가%';

SELECT COUNT(*) FROM HASHTAG WHERE TAG_NAME LIKE #{tagName};

SELECT TAG_NAME FROM HASHTAG WHERE TAG_NAME LIKE #{tagName};

-- 태그 저장용 테이블을 따로 만드는 것이 좋아보임


SELECT * FROM BOARD B JOIN MEMBER M ON (B.MEMBER_NO = M.MEMBER_NO);

